on: [push, pull_request]

name: Continuous integration

jobs:
  ubuntu-build-bundled:
    name: "Ubuntu: Build with bundled libraries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y
          libasound2-dev
          libbz2-dev
          libgl-dev
          libglew-dev
          libjack-dev
          libmad0-dev
          libpulse-dev
          libudev-dev
          libva-dev
          libvorbis-dev
          libxinerama-dev
          libx11-dev
          libxrandr-dev
          libxtst-dev
          nasm
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stepmania-ubuntu-bundled-libraries
          path: |
            Announcers
            Background Effects
            Background Transitions
            BGAnimations
            Characters
            Courses
            Data
            Docs
            NoteSkins
            Scripts
            Songs
            Themes
            stepmania


  ubuntu-build-system:
    name: "Ubuntu: Build with system libraries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y
          libasound2-dev
          libbz2-dev
          libgl-dev
          libglew-dev
          libjack-dev
          libjpeg-dev
          libjsoncpp-dev
          libmad0-dev
          libpcre3-dev
          libpng-dev
          libpulse-dev
          libtomcrypt-dev
          libtommath-dev
          libudev-dev
          libva-dev
          libvorbis-dev
          libxinerama-dev
          libx11-dev
          libxrandr-dev
          libxtst-dev
          ninja-build
      - name: Configure
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
          -DWITH_SYSTEM_GLEW=ON
          -DWITH_SYSTEM_JPEG=ON
          -DWITH_SYSTEM_JSONCPP=ON
          -DWITH_SYSTEM_MAD=ON
          -DWITH_SYSTEM_OGG=ON
          -DWITH_SYSTEM_PCRE=ON
          -DWITH_SYSTEM_PNG=ON
          -DWITH_SYSTEM_TOMCRYPT=ON
          -DWITH_SYSTEM_TOMMATH=ON
          -DWITH_SYSTEM_ZLIB=ON
      - name: Build
        run: cmake --build build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stepmania-ubuntu-system-libraries
          path: |
            Announcers
            Background Effects
            Background Transitions
            BGAnimations
            Characters
            Courses
            Data
            Docs
            NoteSkins
            Scripts
            Songs
            Themes
            stepmania

  macos-build-bundled:
    name: "macOS: Build with bundled libraries"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          brew install yasm
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stepmania-macos
          path: .

  windows-build-bundled:
    name: "Windows: Build with bundled libraries"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Copy build files
        run: cp Program\* .\
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stepmania-windows
          path: |
            Announcers
            Background Effects
            Background Transitions
            BGAnimations
            Characters
            Courses
            Data
            Docs
            NoteSkins
            Scripts
            Songs
            Themes
            Stepmania*.exe
            *.dll

